$modelname "weapons/arc9/darsu_eft/mods/glock_rs.mdl"

$scale 40
$cdmaterials "models/weapons/arc9/darsu_eft/mods/"

$bodygroup "body" {
	studio "sight_rear_glock_glock_std_LOD0_0.smd"
	studio "sight_rear_glock_zev_tech_LOD0_0.smd"
	studio "sight_rear_glock_truglo_tfx_glock_sight_LOD0_0.smd"
	studio "sight_rear_glock_dead_ringer_snake_eyes_glock_sights_LOD0_0.smd"
}

$sequence "idle" {
	"sight_rear_glock_glock_std_LOD0_0.smd"
}