$modelname "weapons/arc9/darsu_eft/mods/mag_glock_pmag_21.mdl"

$scale 40

// $cdmaterials "models/weapons/arc9/darsu_eft/ak/"
// $cdmaterials "models/weapons/arc9/darsu_eft/shared/"
$cdmaterials "models/weapons/arc9/darsu_eft/mods/"

$bodygroup "body"
{
	studio "mag_glock_magpul_pmag_21_gl9_9x19_21_LOD0_0.smd"
}

$sequence "idle" {
	"mag21col.smd"
}

$collisionmodel "mag21col.smd"
{
	$mass 3
}

    