$modelname "weapons/arc9/darsu_eft/mods/mag_glock_bigstick_33.mdl"

$scale 40

// $cdmaterials "models/weapons/arc9/darsu_eft/ak/"
// $cdmaterials "models/weapons/arc9/darsu_eft/shared/"
$cdmaterials "models/weapons/arc9/darsu_eft/mods/"

$bodygroup "body"
{
	studio "mag_glock_glock_big_stick_9x19_33_LOD0_0.smd"
}

$sequence "idle" {
	"mag33col.smd"
}

$collisionmodel "mag33col.smd"
{
	$mass 4
}

    